### PR TITLE
Exposed the method to customize the SessionManager object

### PR DESCRIPTION
**Pull request by adamhathcock**
Exposed the method to customize the SessionManager object

Testing the waters about contributing.  The project I'm about to embark on might need a few more updated passport components with a few extra features spread out.

### CODE REVIEW

**Comment by rwky** [comment]
Can you add a test for this, since it's only a small change a simple test will do.

**Comment by adamhathcock** [comment]
Fixed 👍

**Comment by rwky** [comment]
Wonderful :+1: thanks for the contribution much appreciated :)

**Comment by rwky** [comment]
This is now published in 2.1.0

**Pull request merged**
